spring.application.name=EventApp
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.qrgrgiwbpzabaxowjzgf
spring.datasource.password=lI4lHkn41Ln5yjYy
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate